name: "CI"

on:
  push:
    paths: ~
  workflow_dispatch: ~

jobs:
  hello:
    runs-on: "ubuntu-latest"
    continue-on-error: true
    steps:
      - name: "Hello world"
        run: echo "Hello world"
      - name: "Multiple Lines"
        run: |
          echo "Say"
          exit 1
          echo "Hello"
          echo "To"
          echo "You"
      - name: "List directory"
        run: ls
