name: "CI"

on:
  push:
    paths-ignore: "./ci-basics.yml"
  workflow_dispatch: ~

jobs:
  deps:
    name: "Install depedencies"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - run: ls
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.1
          tools: composer
      - name: "Install composer deps"
        run: |
          export APP_ENV=test
          composer install --prefer-dist --no-interaction --no-progress
