name: "CI"

on:
  push:
    paths-ignore: "./ci-basics.yml"
  workflow_dispatch: ~

jobs:
  deps:
    name: "Install depedencies"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - run: ls
